--以下存储过程设计表结构
CREATE TABLE "ZHJFUAT"."BZ_DATA_REDPACACT_HIS" (
  "HCNO" VARCHAR2(20) NOT NULL ENABLE,
  "REDID" NUMBER(10) NOT NULL ENABLE,
  "OTHERDESC" VARCHAR2(500),
  "OTHERID" VARCHAR2(50) DEFAULT NULL NOT NULL ENABLE,
  "CHANNELNO" VARCHAR2(8) NOT NULL ENABLE,
  "OTHERACTNO" VARCHAR2(50) DEFAULT NULL NOT NULL ENABLE,
  "SENDSTATUS" VARCHAR2(1) DEFAULT NULL,
  "DATADATE" VARCHAR2(8) DEFAULT NULL NOT NULL ENABLE,
  "CREATEDATE" VARCHAR2(8) DEFAULT NULL NOT NULL ENABLE
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "ZHJFUAT"."BZ_DATA_REDPACACT_HIS" IS '标准数据红包历史表';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."HCNO" IS '核心客户号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."REDID" IS '红包ID';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."OTHERDESC" IS '送券说明';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."OTHERID" IS '三方唯一编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."CHANNELNO" IS '商城提供的渠道编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."OTHERACTNO" IS '三方活动编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."SENDSTATUS" IS '送红包状态：0客户不存在 1已送 2红包数据异常未送 3 超出个人领取上线 4 超出红包领取上线';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."DATADATE" IS '账务日期 YYYYMMDD';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."CREATEDATE" IS '写入日期 YYYYMMDD';

CREATE TABLE "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING" (
  "HCNO" VARCHAR2(20) NOT NULL ENABLE,
  "REDID" NUMBER(10) NOT NULL ENABLE,
  "OTHERDESC" VARCHAR2(500),
  "OTHERID" VARCHAR2(50) NOT NULL ENABLE,
  "CHANNELNO" VARCHAR2(8) NOT NULL ENABLE,
  "OTHERACTNO" VARCHAR2(50) NOT NULL ENABLE,
  "DATADATE" VARCHAR2(8) NOT NULL ENABLE,
  "CREATEDATE" VARCHAR2(8) NOT NULL ENABLE
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING" IS '标准任务送红包待送表';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."HCNO" IS '核心客户号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."REDID" IS '红包id';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."OTHERDESC" IS '红包描述';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."OTHERID" IS '第三位系统唯一编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."CHANNELNO" IS '商城系统渠道号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."OTHERACTNO" IS '第三方系统活动编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."DATADATE" IS '账务日期';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."CREATEDATE" IS '创建日期';

CREATE TABLE "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT" (
  "HCNO" VARCHAR2(20) NOT NULL ENABLE,
  "REDID" NUMBER(10) NOT NULL ENABLE,
  "OTHERDESC" VARCHAR2(500),
  "OTHERID" VARCHAR2(50) NOT NULL ENABLE,
  "CHANNELNO" VARCHAR2(8) NOT NULL ENABLE,
  "OTHERACTNO" VARCHAR2(50) NOT NULL ENABLE
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT" IS '标准任务送红包临时表';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."HCNO" IS '核心客户号';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."REDID" IS '红包id';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."OTHERDESC" IS '红包描述';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."OTHERID" IS '第三位系统唯一编号';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."CHANNELNO" IS '商城系统渠道号';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."OTHERACTNO" IS '第三方系统活动编号';

CREATE TABLE "EMALLUAT"."MEMBER" (
  "MEMBERNO" NUMBER(31) NOT NULL ENABLE,
  "LOGINNAME" VARCHAR2(60),
  "LOGINPWD" VARCHAR2(255),
  "MEMBERNAME" VARCHAR2(100),
  "IDTYPE" VARCHAR2(10),
  "IDNO" VARCHAR2(25),
  "GENDER" CHAR(1),
  "PHONENO" VARCHAR2(15),
  "EMAIL" VARCHAR2(50),
  "ADDRESS" VARCHAR2(100),
  "MEMBERLEVEL" CHAR(1),
  "MEMBERSTATUS" CHAR(1),
  "CREATETIME" VARCHAR2(20),
  "LASTLOGINTIME" VARCHAR2(20),
  "LOGINTIMES" NUMBER(31),
  "ERRORLOGINTIMES" NUMBER(31),
  "CUSTOMERSID" NUMBER(31),
  "FROMTYPE" VARCHAR2(2),
  "EXSTATE" VARCHAR2(2),
  "ISCOLLECTSINGLE" CHAR(1),
  "CUSTNO" VARCHAR2(18),
  "ISCUSTSERVER" CHAR(1),
  "MEMBERTYPE" CHAR(1),
  "ISSAVEAUTH" CHAR(1),
  "ISMBAUTH" CHAR(1),
  "ROLEID" NUMBER(31),
  "PAYPWD" VARCHAR2(100),
  "SECQUESTION1" VARCHAR2(255),
  "SECANSWER1" VARCHAR2(255),
  "SECQUESTION2" VARCHAR2(255),
  "SECANSWER2" VARCHAR2(255),
  "SECQUESTION3" VARCHAR2(255),
  "SECANSWER3" VARCHAR2(255),
  "LASTLOGINDATE" VARCHAR2(18),
  "ACCOUNTAUTH" CHAR(1),
  "ERRORPAYTIMES" NUMBER(31),
  "SUBTYPE" CHAR(4),
  "IMGURL" VARCHAR2(100),
  "LOCKPAYPASSWORDDATE" VARCHAR2(20),
  "ISLOCKPAYPASSWORD" CHAR(1) DEFAULT '0',
  "LOCKLOGINPASSWORDDATE" VARCHAR2(20),
  "CHANNEL" VARCHAR2(3),
  "ISOPENEMALL" VARCHAR2(1),
  "ISOPENEPAY" VARCHAR2(1),
  "INSTITUTIONID" NUMBER(8),
  "ISBATCH" VARCHAR2(1),
  "NICKNAME" VARCHAR2(100),
  "MEMBERIMAGES" VARCHAR2(500),
  "HOSTCUSTNO" VARCHAR2(32),
  "WECHATPUSH" VARCHAR2(1),
  CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBERNO"),
  CONSTRAINT "MEMBER_IX1" UNIQUE ("LOGINNAME"),
  CONSTRAINT "MEMBER_IX3" UNIQUE ("EMAIL")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."MEMBER" IS '门户会员表';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERNO" IS '会员号<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOGINNAME" IS '会员名<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOGINPWD" IS '登录密码，密文<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERNAME" IS '姓名<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."IDTYPE" IS '证件类型<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."IDNO" IS '证件号码<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."GENDER" IS '性别，1男，2女<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."PHONENO" IS '手机号<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."EMAIL" IS '邮箱<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ADDRESS" IS '地址<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERLEVEL" IS '客户';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERSTATUS" IS '客户状态，1正常，2未激活，3注销，4锁定';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."CREATETIME" IS '创建时间<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LASTLOGINTIME" IS '最近登录时间';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOGINTIMES" IS '累计登录次数<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ERRORLOGINTIMES" IS '累计登录错误次数，每次登录成功后置0，累计5次状态锁定。<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."CUSTOMERSID" IS '客户ID<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."FROMTYPE" IS '会员来源类型 00 自助注册 11 网银自动注册<BR>00 是缺省值<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."EXSTATE" IS '会员扩展状态<BR>00 是缺省值<BR>10 网银自动注册状态<BR>11 已修改设置登录名<BR>12 已修改设置登录密码<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISCOLLECTSINGLE" IS '是否开通商户收单服务 0-开通 1-不开通（默认）<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."CUSTNO" IS '商户号（开通了商户的才会有商户号）<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISCUSTSERVER" IS '是否开通店家服务<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERTYPE" IS '会员类型（个人，企业） 0个人，1企业<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISSAVEAUTH" IS '是否开启安全密码认证 0-开通 1-不开通';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISMBAUTH" IS '<BR>是否开启手机认证 0-开通 1-不开通<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ROLEID" IS '角色编号';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."PAYPWD" IS '支付密码';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECQUESTION1" IS '安全保护问题1';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECANSWER1" IS '安全保护应答1';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECQUESTION2" IS '安全保护问题2';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECANSWER2" IS '安全保护应答2';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECQUESTION3" IS '安全保护问题3';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECANSWER3" IS '安全保护应答3';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LASTLOGINDATE" IS '上次登录时间';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ACCOUNTAUTH" IS '账号实名认证标志；0未认证 1已认证；商户审批时必须已认证状态才进入审批状态，未认证提示商户添加银行账号做实名认证；';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ERRORPAYTIMES" IS '错误支付次数';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SUBTYPE" IS '1001 店铺主账号, 1002 店铺网点子账号, 1003 承运商物流网点子账号,2001 装修公司子账号';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."IMGURL" IS '会员头像';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOCKPAYPASSWORDDATE" IS '支付密码锁定时间';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISLOCKPAYPASSWORD" IS '支付密码是否锁定: 0-不锁定 1-锁定';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOCKLOGINPASSWORDDATE" IS '登录密码锁定时间';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."CHANNEL" IS '渠道';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISOPENEMALL" IS '是否开启商城';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISOPENEPAY" IS '是否开启易支付';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."INSTITUTIONID" IS '机构号，批量导入时会数据';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISBATCH" IS '是否批量导入，0：是，1：否';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."NICKNAME" IS '昵称';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERIMAGES" IS '会员图片';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."HOSTCUSTNO" IS '核心客户号';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."WECHATPUSH" IS '是否接受微信推送';

CREATE TABLE "EMALLUAT"."REDPACACT" (
  "PACID" NUMBER(31) NOT NULL ENABLE,
  "ACTNAME" VARCHAR2(200) NOT NULL ENABLE,
  "STARTDATE" VARCHAR2(12) DEFAULT NULL NOT NULL ENABLE,
  "ENDDATE" VARCHAR2(12) DEFAULT NULL NOT NULL ENABLE,
  "STARTTIME" VARCHAR2(12) NOT NULL ENABLE,
  "ENDTIME" VARCHAR2(12) NOT NULL ENABLE,
  "AUTHSTATE" VARCHAR2(4) NOT NULL ENABLE,
  "PCINHTMLURL" VARCHAR2(200),
  "PCALERTHEMLURL" VARCHAR2(200),
  "MBINHTMLURL" VARCHAR2(200),
  "MBALERTHEMLURL" VARCHAR2(200),
  "PACTYPE" VARCHAR2(4) NOT NULL ENABLE,
  "FLAG" VARCHAR2(2) NOT NULL ENABLE,
  "BELONGTYPE" VARCHAR2(4) NOT NULL ENABLE,
  "USERULEDESC" VARCHAR2(2000),
  "ORIGINATOR" VARCHAR2(100) NOT NULL ENABLE,
  "SHOPID" NUMBER(31),
  "MAXSEND" NUMBER(31) NOT NULL ENABLE,
  "VALIDAY" NUMBER(8) DEFAULT '0',
  "RPENDTIME" VARCHAR2(30),
  "STATE" VARCHAR2(10),
  "USESTARTTIME" VARCHAR2(30),
  "USEENDTIME" VARCHAR2(30),
  "LIMITCOUNT" NUMBER(8) DEFAULT '1',
  "USEBALANCE" NUMBER(18,2),
  "DAYCNT" NUMBER(8) DEFAULT '1',
  "INSNO" VARCHAR2(8),
  "PACAMTMIN" NUMBER(18,2) NOT NULL ENABLE,
  "PACAMTMAX" NUMBER(18,2),
  "SHOPIDS" VARCHAR2(2000) DEFAULT NULL,
  "REMARK" VARCHAR2(300),
  "ACTTYPE" VARCHAR2(10),
  "CATEGORY2ID" VARCHAR2(2000) DEFAULT NULL,
  "USEDESC" VARCHAR2(200),
  "IMAGEURL" VARCHAR2(200),
  "MATCHTYPE" VARCHAR2(2),
  "GOODSID" VARCHAR2(3000) DEFAULT NULL,
  "LISTATTRIBUTE" VARCHAR2(1),
  "LISTTYPE" VARCHAR2(1),
  "LIMITTYPE" VARCHAR2(1),
  "ISVISIBLE" VARCHAR2(1),
  "ISTRANSFER" VARCHAR2(1),
  "ISBUY" VARCHAR2(3),
  "INSTITUTIONNO" VARCHAR2(10),
  "ISBACK" VARCHAR2(1),
  "BACKINGNUM" NUMBER(8) DEFAULT 1,
  "BZ1" VARCHAR2(20),
  "BZ2" VARCHAR2(20),
  "BZ3" VARCHAR2(20),
  "BZ4" VARCHAR2(20),
  "BZ5" VARCHAR2(20),
  "BZ6" VARCHAR2(20),
  CONSTRAINT "PK_REDPACACT" PRIMARY KEY ("PACID")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."REDPACACT" IS '红包活动表';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PACID" IS '主键，自增长ID';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ACTNAME" IS '红包活动名称';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."STARTDATE" IS '开始日期';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ENDDATE" IS '结束日期';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."STARTTIME" IS '开始时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ENDTIME" IS '结束时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."AUTHSTATE" IS '审核状态: 1001-待审核<BR>1002-审核通过<BR>1003-审核失败<BR>';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PCINHTMLURL" IS 'PC端活动入口页面URL';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PCALERTHEMLURL" IS 'PC端参入活动弹出页面URL';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."MBINHTMLURL" IS '手机端活动入口页面URL';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."MBALERTHEMLURL" IS '手机端参入活动弹出页面URL';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PACTYPE" IS '红包类型 1001-固定,1002-随机固定值,1003-随机区间值';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."FLAG" IS '活动标识 1:注册时领取';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BELONGTYPE" IS '发行方 1001-平台, 1002-店铺';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USERULEDESC" IS '使用规则描述';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ORIGINATOR" IS '发起人';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."SHOPID" IS '店铺ID, 如果BELONGTYPE为2时则必填';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."MAXSEND" IS '最多送出个数';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."VALIDAY" IS '有效期，自活动结束后多少天失效，单位/天';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."RPENDTIME" IS '红包有效日期';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."STATE" IS '00：启用，11：停用';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USESTARTTIME" IS '使用开始时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USEENDTIME" IS '使用结束时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."LIMITCOUNT" IS '活动有效期内可领取数量';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USEBALANCE" IS '使用金额限制';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."DAYCNT" IS '每天可领取数量';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."INSNO" IS '所属机构编号';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PACAMTMIN" IS '红包金额';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PACAMTMAX" IS '结算金额';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."SHOPIDS" IS '店铺id集合';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."REMARK" IS '审核意见';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ACTTYPE" IS '0：红包 1：优惠券';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."CATEGORY2ID" IS '所属2级类目id';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USEDESC" IS '图文详情';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."IMAGEURL" IS '代金券图片';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."MATCHTYPE" IS '匹配类型  0-全匹配  1-模糊匹配';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."GOODSID" IS '商品编号';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."LISTATTRIBUTE" IS '名单属性 0-白名单,1-黑名单';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."LISTTYPE" IS '名单类型 0-手机号码,1-客户号';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."LIMITTYPE" IS '允许类型 0-允许店铺,1-允许类目,2-允许商品';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ISVISIBLE" IS '页面是否可见 Y:可见 N:不可见';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ISTRANSFER" IS '是否允许转赠 Y:允许 N:不允许';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ISBUY" IS '是否需要购买 000-不需要购买 001-需要购买';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."INSTITUTIONNO" IS '机构号，关联机构表INSTITUTION';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ISBACK" IS '可退标志，0-可退，1-不可退';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BACKINGNUM" IS '可退次数，默认1次';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ1" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ2" IS '投放渠道（取自枚举订单渠道）';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ3" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ4" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ5" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ6" IS '备用字段';


CREATE TABLE "EMALLUAT"."MYREDPAC" (
  "MYPACID" NUMBER(31) NOT NULL ENABLE,
  "MEMBERNO" NUMBER(31) NOT NULL ENABLE,
  "PACID" NUMBER(31) NOT NULL ENABLE,
  "PACSTATE" VARCHAR2(4) NOT NULL ENABLE,
  "INITAMT" NUMBER(18,2) NOT NULL ENABLE,
  "BELONGTYPE" VARCHAR2(4) NOT NULL ENABLE,
  "CREATETIME" VARCHAR2(30),
  "RECORDID" VARCHAR2(50),
  "REFUNDTIMES" NUMBER(31),
  CONSTRAINT "PK_MYREDPAC" PRIMARY KEY ("MYPACID")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."MYREDPAC" IS '我的红包表';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."MYPACID" IS '主键，自增长ID';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."MEMBERNO" IS '会员号';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."PACID" IS '红包ID';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."PACSTATE" IS '红包状态 <BR>1001-锁定,<BR>1002-正常待使用,<BR>1003-已使用（已下单，未付款）,<BR>1004-退款,1005-过期 <BR>1006-待清算 <BR>1007-已支付（支付成功）<BR>1008-失效状态,1009-已清算';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."INITAMT" IS '原始金额';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."BELONGTYPE" IS '发行方 1001-平台, 1002-店铺';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."RECORDID" IS '手机银行红包记录 32位';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."REFUNDTIMES" IS '商品消费退款后，红包的已退次数';


CREATE TABLE "EMALLUAT"."REDPACAPPLY" (
  "ID" NUMBER(8) NOT NULL ENABLE,
  "BATCHID" VARCHAR2(50),
  "APPLYBY" VARCHAR2(25),
  "APPLYTIME" VARCHAR2(30),
  "SUMCOUNT" NUMBER(8),
  "SUCCCOUNT" NUMBER(8),
  "FAILCOUNT" NUMBER(8),
  "PACID" NUMBER(8),
  "TYPE" VARCHAR2(1),
  "SENDREASON" VARCHAR2(400),
  "SENDACTNO" VARCHAR2(50)
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."REDPACAPPLY" IS '红包清算申请表';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."ID" IS '主键';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."BATCHID" IS '申请批次';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."APPLYBY" IS '申请人';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."APPLYTIME" IS '申请时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."SUMCOUNT" IS '总条数';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."SUCCCOUNT" IS '送红包成功条数';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."FAILCOUNT" IS '送红包失败条数';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."PACID" IS '红包活动Id';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."TYPE" IS '1：手机，2：邮箱，3：会员号';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."SENDREASON" IS '送券说明（esb与优讯渠道送券新增）';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."SENDACTNO" IS '三方活动编号（esb与优讯渠道送券新增）';


CREATE TABLE "EMALLUAT"."REDPACAPPLYDETAIL" (
  "ID" NUMBER(8) NOT NULL ENABLE,
  "PHONENO" VARCHAR2(20),
  "BATCHID" VARCHAR2(50),
  "MEMBERNO" NUMBER(8),
  "EMAIL" VARCHAR2(50),
  "CREATETIME" VARCHAR2(30),
  "STATUS" VARCHAR2(1),
  "CUSTNO" VARCHAR2(30)
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."REDPACAPPLYDETAIL" IS '红包清算申请细节';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."ID" IS '主键';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."PHONENO" IS '手机号';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."BATCHID" IS '批次号';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."MEMBERNO" IS '会员号';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."STATUS" IS '1：待送红包，2：送红包成功，3：送红包失败';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."CUSTNO" IS '客户号（根据redpacapply表的type字段区分）';


CREATE TABLE "EMALLUAT"."PRIVI_REDPACACT" (
  "ID" NUMBER(31) NOT NULL ENABLE,
  "CUSTTYPE" VARCHAR2(4) NOT NULL ENABLE,
  "CUSTNO" VARCHAR2(20) DEFAULT NULL NOT NULL ENABLE,
  "REDID" NUMBER(31) DEFAULT NULL NOT NULL ENABLE,
  "OTHERDESC" VARCHAR2(500) DEFAULT NULL,
  "OTHERID" VARCHAR2(20) DEFAULT NULL,
  "CHANNELNO" VARCHAR2(8) NOT NULL ENABLE,
  "DATASOURCE" NUMBER(1),
  "OTHERACTNO" VARCHAR2(20),
  "CREATEDATE" VARCHAR2(12) NOT NULL ENABLE,
  "BZ1" VARCHAR2(20) DEFAULT 0,
  "BZ2" VARCHAR2(20),
  "BZ3" VARCHAR2(20),
  "BZ4" VARCHAR2(20),
  "BZ5" VARCHAR2(20),
  "BZ6" VARCHAR2(20),
  "BZ7" VARCHAR2(20),
  "BZ8" VARCHAR2(20),
  "BZ9" VARCHAR2(20),
  "BZ10" VARCHAR2(20),
  "STATUS" NUMBER(1) DEFAULT 0 NOT NULL ENABLE,
  "REDNAME" VARCHAR2(200) DEFAULT NULL,
  "MEMBERNO" NUMBER(31) DEFAULT NULL,
  CONSTRAINT "PK_PRIVI_REDPACACT" PRIMARY KEY ("ID")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."PRIVI_REDPACACT" IS '待送红包表';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."ID" IS '主键，自增长ID';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."CUSTTYPE" IS '客户类型：HCNO核心客户号，10 手机号，11 邮箱，12 商城会员号';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."CUSTNO" IS '结合客户类型';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."REDID" IS '红包ID';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."OTHERDESC" IS '送券说明';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."OTHERID" IS '三方唯一编号';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."CHANNELNO" IS '商城提供的渠道编号：商城管理台：000';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."DATASOURCE" IS '数据源：1 积分跑批 2 外放接口 3 商城管理台手工赠送';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."OTHERACTNO" IS '三方活动编号';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."CREATEDATE" IS '日期：YYYYMMDD';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ1" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ2" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ3" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ4" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ5" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ6" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ7" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ8" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ9" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ10" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."STATUS" IS '0：启用 1：停用';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."REDNAME" IS '红包名称';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."MEMBERNO" IS '商城会员号';





CREATE OR REPLACE PROCEDURE P_BATCH_SEND_REDPAC(p_day IN NUMBER DEFAULT 30)
-- ============================================================
-- 存储过程：P_BATCH_SEND_REDPAC
-- 功能：批量送红包
-- 业务逻辑：
-- 1. 从临时表和待送表获取待处理数据
-- 2. 按以下步骤过滤：
--    a) 过滤客户不存在的记录，写入BZ_DATA_REDPACACT_HIS和PRIVI_REDPACACT
--    b) 过滤无效红包（不存在/未审核/已过期等）,除不存在的其他其他情况都写入PRIVI_REDPACACT
--    c) 过滤超出个人限制的记录
--    d) 过滤超出红包总数限制的记录
-- 3. 将符合条件的记录写入商城库
-- 4. 记录处理结果到历史表
--    a) 存在的跳过不做处理
--    b) 不存在的插入
-- 5. 清理待送红包表超过p_day天的数据
-- ============================================================
IS
    v_now     VARCHAR2(14);  -- 时间戳
    v_now1     VARCHAR2(20);  -- 送红包明细表时间
    v_now2     VARCHAR2(20);  -- 我的红包创建时间
    v_now3     VARCHAR2(20);  -- 处理时间经过
    v_today   VARCHAR2(8); 
    v_batchid VARCHAR2(16); -- 批次号
    v_cnt     NUMBER;  -- 数据数量
     --账务日期
    l_accdate varchar2(8);
    v_sql varchar2(32767);
    v_errorInfo varchar2(2000) default '';
    
    -- 各类数据处理计数（替代PL/SQL集合，数据全程留在GTT中）
    v_final_ok_count      NUMBER := 0;
    v_invalid_pac_count   NUMBER := 0;
    v_limit_fail_count    NUMBER := 0;
    v_maxsend_fail_count  NUMBER := 0;
    v_no_member_count     NUMBER := 0;

BEGIN
    /** OB库有超时限制，增加超时时长 **/
    EXECUTE IMMEDIATE 'SET ob_query_timeout = 86400000000';
    -- 步骤1：初始化变量
    v_now     := TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS');
    v_now1     := TO_CHAR(SYSDATE, 'YYYY-MM-DD hh24:mm:ss');
    v_now2     := TO_CHAR(SYSDATE, 'YYYYMMDD hh24:mm:ss');
    v_now3     := TO_CHAR(SYSDATE, 'YYYYMMDD hh24:mm:ss');
    v_today   := TO_CHAR(SYSDATE, 'YYYYMMDD');
    v_batchid := 'P' || v_now;
    DBMS_OUTPUT.PUT_LINE('处理开始时间：' || v_now3);
    select sp.sysworkdate into l_accdate from sysparameter sp;

    /* ================== 步骤2：检查是否有待处理数据 ================== */
    SELECT COUNT(1)
      INTO v_cnt
      FROM (
            SELECT 1 FROM ZHJFUAT.QS_TEMP_BZ_DATA_REDPACACT
            UNION ALL
            SELECT 1 FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING
           );

    IF v_cnt = 0 THEN
        DBMS_OUTPUT.PUT_LINE('没有待处理的红包数据');
        -- 清理数据：p_day=0 时清空整个待送表，p_day>0 时清理超过p_day天的数据
        IF p_day = 0 THEN
            EXECUTE IMMEDIATE 'TRUNCATE TABLE ZHJFUAT.BZ_DATA_REDPACACT_SENDING';
        ELSE
            DELETE FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING
            WHERE CREATEDATE < TO_CHAR(SYSDATE - p_day, 'YYYYMMDD');
        END IF;
        COMMIT;
        RETURN;
    END IF;

    /* ================== 步骤3：识别客户不存在的记录（写入GTT替代PL/SQL集合） ================== */
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_no_member';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    EXECUTE IMMEDIATE '
        CREATE GLOBAL TEMPORARY TABLE temp_no_member ON COMMIT PRESERVE ROWS AS
        SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, DATATYPE
        FROM (
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, 0 AS DATATYPE
              FROM ZHJFUAT.QS_TEMP_BZ_DATA_REDPACACT
            UNION ALL
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, 1 AS DATATYPE
              FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING
        ) s
        WHERE NOT EXISTS (
            SELECT 1 FROM EMALLUAT.MEMBER m WHERE m.HOSTCUSTNO = s.HCNO
        )';

    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM temp_no_member' INTO v_no_member_count;

    /* ================== 步骤4：处理客户不存在的记录 ================== */
    IF v_no_member_count > 0 THEN
        -- ① 写入待送表（仅临时表来源数据）
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_SENDING
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''' || l_accdate || ''', ''' || v_today || '''
            FROM temp_no_member WHERE DATATYPE = 0';

        -- ② 写入历史表（客户不存在）
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
             SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''0'', ''' || l_accdate || ''', ''' || v_today || '''
            FROM temp_no_member WHERE DATATYPE = 0';

        -- ③ 写入EMALLUAT待送红包表（仅REDID在REDPACACT中存在的记录）
        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.PRIVI_REDPACACT
            (ID, CUSTTYPE, CUSTNO, REDID, OTHERDESC, OTHERID, CHANNELNO,
             DATASOURCE, OTHERACTNO, CREATEDATE, STATUS)
            SELECT EMALLUAT.S_PRIVI_REDPACACT.NEXTVAL,
                   ''HCNO'', HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO,
                   1, OTHERACTNO, ''' || v_today || ''', 0
            FROM temp_no_member
            WHERE DATATYPE = 0
              AND EXISTS (SELECT 1 FROM EMALLUAT.REDPACACT r WHERE r.PACID = REDID)';
    END IF;

    -- 清理客户不存在临时表
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_no_member';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    /* ================== 步骤5：核心业务逻辑 - 红包发放处理 ================== */
    -- 创建全局临时表来存储中间结果
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_with_redpac';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE temp_with_redpac ON COMMIT PRESERVE ROWS AS
        SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, 
               DATATYPE, MEMBERNO, PACAMTMIN, LIMITCOUNT, MAXSEND,
               CASE 
                 WHEN PACID IS NULL THEN ''N''  -- 红包不存在
                 WHEN AUTHSTATE != ''1002'' THEN ''N''  -- 审核未通过
                 WHEN STATE != ''00'' THEN ''N''  -- 红包未启用
                 WHEN NVL(USEENDTIME, ''9999-12-31 23:59:59'') < ''' || v_now1 || ''' THEN ''N''  -- 已过期
                 ELSE ''Y''
               END AS IS_VALID
        FROM (
            SELECT wm.HCNO, wm.REDID, wm.OTHERDESC, wm.OTHERID, wm.CHANNELNO, wm.OTHERACTNO, 
                   wm.DATATYPE, wm.MEMBERNO, r.PACAMTMIN, r.LIMITCOUNT, r.MAXSEND,
                   r.PACID, r.AUTHSTATE, r.STATE, r.USEENDTIME
            FROM (
                SELECT s.HCNO, s.REDID, s.OTHERDESC, s.OTHERID, s.CHANNELNO, s.OTHERACTNO, 
                       s.DATATYPE, m.MEMBERNO
                FROM (
                    SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, 
                           0 AS DATATYPE
                    FROM ZHJFUAT.QS_TEMP_BZ_DATA_REDPACACT
                    UNION ALL
                    SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                           1 AS DATATYPE
                    FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING
                ) s
                JOIN EMALLUAT.MEMBER m ON m.HOSTCUSTNO = s.HCNO
            ) wm
            LEFT JOIN EMALLUAT.REDPACACT r ON r.PACID = wm.REDID
        )';

    -- 计算已发送红包数量并存储到另一个临时表
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_sent_counts';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE temp_sent_counts ON COMMIT PRESERVE ROWS AS
        WITH member_ranked AS (
            SELECT wr.*,
                   (SELECT COUNT(1)
                      FROM EMALLUAT.MYREDPAC m
                     WHERE m.MEMBERNO = wr.MEMBERNO
                       AND m.PACID = wr.REDID) AS SENT_BY_MEMBER,
                   ROW_NUMBER() OVER(
                       PARTITION BY wr.MEMBERNO, wr.REDID
                       ORDER BY wr.OTHERID
                   ) AS RN_MEMBER_RED
            FROM temp_with_redpac wr
            WHERE wr.IS_VALID = ''Y''
        ),
        limit_ok AS (
            SELECT mr.*
            FROM member_ranked mr
            WHERE mr.RN_MEMBER_RED + mr.SENT_BY_MEMBER <= mr.LIMITCOUNT
        )
        SELECT lo.*,
               (SELECT COUNT(1)
                  FROM EMALLUAT.MYREDPAC m
                 WHERE m.PACID = lo.REDID) AS SENT_TOTAL,
               ROW_NUMBER() OVER(
                   PARTITION BY lo.REDID
                   ORDER BY lo.OTHERID
               ) AS RN_RED
        FROM limit_ok lo';

    /* ================== 步骤5.1：统计各类数据计数 ================== */
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM temp_with_redpac WHERE IS_VALID = ''N'''
        INTO v_invalid_pac_count;

    EXECUTE IMMEDIATE '
        SELECT COUNT(*)
        FROM temp_with_redpac wr
        WHERE wr.IS_VALID = ''Y''
          AND NOT EXISTS (SELECT 1 FROM temp_sent_counts sc
                           WHERE sc.HCNO = wr.HCNO
                             AND sc.REDID = wr.REDID
                             AND sc.OTHERID = wr.OTHERID)'
        INTO v_limit_fail_count;

    EXECUTE IMMEDIATE '
        SELECT COUNT(*)
        FROM temp_sent_counts sc
        WHERE sc.RN_MEMBER_RED + sc.SENT_BY_MEMBER <= sc.LIMITCOUNT
          AND sc.RN_RED + sc.SENT_TOTAL > sc.MAXSEND'
        INTO v_maxsend_fail_count;

    /* ================== 步骤6：写历史记录/待送表（纯SQL批量写入） ================== */
    -- 无效红包记录（IS_VALID='N'）
    IF v_invalid_pac_count > 0 THEN
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
             SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''2'', ''' || l_accdate || ''', ''' || v_today || '''
            FROM temp_with_redpac WHERE IS_VALID = ''N'' AND DATATYPE = 0';

        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.PRIVI_REDPACACT
            (ID, CUSTTYPE, CUSTNO, REDID, OTHERDESC, OTHERID, CHANNELNO,
             DATASOURCE, OTHERACTNO, CREATEDATE, STATUS, MEMBERNO)
            SELECT EMALLUAT.S_PRIVI_REDPACACT.NEXTVAL, ''HCNO'', HCNO, REDID,
                   OTHERDESC, OTHERID, CHANNELNO, 1, OTHERACTNO, ''' || v_today || ''', 0, MEMBERNO
            FROM temp_with_redpac
            WHERE IS_VALID = ''N'' AND DATATYPE = 0
              AND EXISTS (SELECT 1 FROM EMALLUAT.REDPACACT r WHERE r.PACID = REDID)';
    END IF;

    -- 超出个人限制的记录（temp_with_redpac中有但temp_sent_counts中无的行）
    IF v_limit_fail_count > 0 THEN
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_SENDING
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''' || l_accdate || ''', ''' || v_today || '''
            FROM temp_with_redpac wr
            WHERE wr.IS_VALID = ''Y'' AND wr.DATATYPE = 0
              AND NOT EXISTS (SELECT 1 FROM temp_sent_counts sc
                               WHERE sc.HCNO = wr.HCNO
                                 AND sc.REDID = wr.REDID
                                 AND sc.OTHERID = wr.OTHERID)';

        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
             SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''3'', ''' || l_accdate || ''', ''' || v_today || '''
            FROM temp_with_redpac wr
            WHERE wr.IS_VALID = ''Y'' AND wr.DATATYPE = 0
              AND NOT EXISTS (SELECT 1 FROM temp_sent_counts sc
                               WHERE sc.HCNO = wr.HCNO
                                 AND sc.REDID = wr.REDID
                                 AND sc.OTHERID = wr.OTHERID)';
    END IF;

    -- 超出红包总数限制的记录
    IF v_maxsend_fail_count > 0 THEN
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_SENDING
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''' || l_accdate || ''', ''' || v_today || '''
            FROM temp_sent_counts sc
            WHERE sc.RN_MEMBER_RED + sc.SENT_BY_MEMBER <= sc.LIMITCOUNT
              AND sc.RN_RED + sc.SENT_TOTAL > sc.MAXSEND AND sc.DATATYPE = 0';

        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
             SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''4'', ''' || l_accdate || ''', ''' || v_today || '''
            FROM temp_sent_counts sc
            WHERE sc.RN_MEMBER_RED + sc.SENT_BY_MEMBER <= sc.LIMITCOUNT
              AND sc.RN_RED + sc.SENT_TOTAL > sc.MAXSEND AND sc.DATATYPE = 0';
    END IF;

    /* ================== 步骤7：发送红包到商城系统 ================== */
    -- 先统计成功数据量
    EXECUTE IMMEDIATE '
        SELECT COUNT(*)
        FROM temp_sent_counts sc
        WHERE sc.RN_MEMBER_RED + sc.SENT_BY_MEMBER <= sc.LIMITCOUNT
          AND sc.RN_RED + sc.SENT_TOTAL <= sc.MAXSEND'
        INTO v_final_ok_count;

    IF v_final_ok_count > 0 THEN
        -- 创建扩容的temp_final_ok（含MEMBERNO/PACAMTMIN/DATATYPE）
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE temp_final_ok';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;

        EXECUTE IMMEDIATE '
            CREATE GLOBAL TEMPORARY TABLE temp_final_ok ON COMMIT PRESERVE ROWS AS
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   CAST(NULL AS VARCHAR2(8)) AS DATADATE,
                   CAST(NULL AS VARCHAR2(8)) AS CREATEDATE,
                   MEMBERNO, PACAMTMIN, DATATYPE
            FROM temp_sent_counts WHERE 1=0';

        -- ★ 一次INSERT替代 BULK COLLECT + FOR LOOP EXECUTE IMMEDIATE
        EXECUTE IMMEDIATE '
            INSERT INTO temp_final_ok
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''' || l_accdate || ''', ''' || v_today || ''', MEMBERNO, PACAMTMIN, DATATYPE
            FROM temp_sent_counts sc
            WHERE sc.RN_MEMBER_RED + sc.SENT_BY_MEMBER <= sc.LIMITCOUNT
              AND sc.RN_RED + sc.SENT_TOTAL <= sc.MAXSEND';

        -- 7.1 写REDPACAPPLY表（按REDID+CHANNELNO+OTHERDESC+OTHERACTNO分组）
        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.REDPACAPPLY
            (ID, BATCHID, APPLYBY, APPLYTIME, SUMCOUNT, SUCCCOUNT,
             FAILCOUNT, PACID, TYPE, SENDREASON, SENDACTNO)
            SELECT EMALLUAT.S_REDPACAPPLY.NEXTVAL,
                   BATCHID,
                   CHANNELNO,
                   APPLYTIME,
                   SUMCOUNT,
                   SUCCCOUNT,
                   FAILCOUNT,
                   REDID,
                   TYPE,
                   OTHERDESC,
                   OTHERACTNO
              FROM (
                    SELECT ''' || v_batchid || ''' AS BATCHID,
                           CHANNELNO,
                           ''' || v_now1 || ''' AS APPLYTIME,
                           COUNT(*) AS SUMCOUNT,
                           0 AS SUCCCOUNT,
                           COUNT(*) AS FAILCOUNT,
                           REDID,
                           ''4'' AS TYPE,
                           OTHERDESC,
                           OTHERACTNO
                      FROM temp_final_ok
                     GROUP BY REDID, CHANNELNO, OTHERDESC, OTHERACTNO
                   )';

        -- 7.2 写REDPACAPPLYDETAIL表（★ 一条INSERT...SELECT替代FORALL）
        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.REDPACAPPLYDETAIL
            (ID, PHONENO, BATCHID, MEMBERNO, EMAIL, CREATETIME, STATUS, CUSTNO)
            SELECT EMALLUAT.S_REDPACAPPLYDETAIL.NEXTVAL,
                   NULL, ''' || v_batchid || ''', 0, NULL, ''' || v_now1 || ''', ''3'', HCNO
            FROM temp_final_ok';

        -- 7.3 写MYREDPAC表（★ 一条INSERT...SELECT替代FORALL）
        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.MYREDPAC
            (MYPACID, MEMBERNO, PACID, PACSTATE, INITAMT,
             BELONGTYPE, CREATETIME, RECORDID, REFUNDTIMES)
            SELECT EMALLUAT.S_MYREDPAC.NEXTVAL,
                   MEMBERNO, REDID, ''1002'', PACAMTMIN,
                   ''1001'', ''' || v_now2 || ''', NULL, 0
            FROM temp_final_ok';

        -- 7.4 更新REDPACAPPLY表（按分组匹配更新成功数量）
        EXECUTE IMMEDIATE '
            UPDATE EMALLUAT.REDPACAPPLY ra
               SET (SUCCCOUNT, FAILCOUNT) = (
                       SELECT COUNT(*), 0
                         FROM temp_final_ok t
                        WHERE t.REDID = ra.PACID
                          AND t.CHANNELNO = ra.APPLYBY
                          AND t.OTHERDESC = ra.SENDREASON
                          AND t.OTHERACTNO = ra.SENDACTNO
                   )
             WHERE ra.BATCHID = ''' || v_batchid || '''';

        -- 7.5 更新REDPACAPPLYDETAIL表（更新状态和会员号）
        UPDATE EMALLUAT.REDPACAPPLYDETAIL d
           SET STATUS = '2',  -- 成功状态
               MEMBERNO = (
                   SELECT MIN(m.MEMBERNO)
                     FROM EMALLUAT.MEMBER m
                    WHERE m.HOSTCUSTNO = d.CUSTNO
               )
         WHERE d.BATCHID = v_batchid;

        -- 7.6 写成功记录到历史表（仅插入不存在的，已存在的跳过）
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
                (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO,
                 OTHERACTNO, SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO,
                   OTHERACTNO, ''1'', DATADATE, CREATEDATE
              FROM temp_final_ok src
             WHERE NOT EXISTS (
                       SELECT 1 FROM ZHJFUAT.BZ_DATA_REDPACACT_HIS his
                        WHERE his.CHANNELNO = src.CHANNELNO
                          AND his.OTHERID = src.OTHERID
                          AND his.OTHERACTNO = src.OTHERACTNO
                   )';

        -- 7.7 清理已成功发送的待送表记录（★ 一条DELETE替代FOR LOOP）
        EXECUTE IMMEDIATE '
            DELETE FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING s
            WHERE EXISTS (
                SELECT 1 FROM temp_final_ok t
                WHERE t.HCNO = s.HCNO
                  AND t.REDID = s.REDID
                  AND t.OTHERID = s.OTHERID
                  AND t.DATATYPE = 1
            )';

        -- 清理temp_final_ok
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE temp_final_ok';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END IF;

    /* ================== 步骤8：清理数据 ================== */
    IF p_day = 0 THEN
        EXECUTE IMMEDIATE 'TRUNCATE TABLE ZHJFUAT.BZ_DATA_REDPACACT_SENDING';
    ELSE
        DELETE FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING
         WHERE CREATEDATE <= TO_CHAR(SYSDATE - p_day, 'YYYYMMDD');
    END IF;

    /* ================== 步骤9：清理临时表 ================== */
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_with_redpac';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;
    
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_sent_counts';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    /* ================== 步骤10：提交事务 ================== */
    COMMIT;
    
    /* ================== 步骤11：输出处理日志 ================== */
    DBMS_OUTPUT.PUT_LINE('========== 批量送红包处理完成 ==========');
    DBMS_OUTPUT.PUT_LINE('处理时间：' || v_now);
    DBMS_OUTPUT.PUT_LINE('处理完成时间：' || v_now3);
    DBMS_OUTPUT.PUT_LINE('批次号：' || v_batchid);
    DBMS_OUTPUT.PUT_LINE('成功发送红包数：' || v_final_ok_count);
    DBMS_OUTPUT.PUT_LINE('客户不存在数：' || v_no_member_count);
    DBMS_OUTPUT.PUT_LINE('无效红包数：' || v_invalid_pac_count);
    DBMS_OUTPUT.PUT_LINE('超出个人限制数：' || v_limit_fail_count);
    DBMS_OUTPUT.PUT_LINE('超出红包总数限制数：' || v_maxsend_fail_count);
    DBMS_OUTPUT.PUT_LINE('清理超过' || p_day || '天的待送表数据');
    DBMS_OUTPUT.PUT_LINE('=========================================');

EXCEPTION
  WHEN OTHERS THEN
  BEGIN
    -- 清理临时表（如果存在）
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_with_redpac';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;
    
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_sent_counts';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_final_ok';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE temp_no_member';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    ROLLBACK;
    v_errorInfo := DBMS_UTILITY.FORMAT_ERROR_BACKTRACE||' ** '||SQLCODE||' ** '||SQLERRM;
    v_sql := 'insert into t_proc_oper_log(PROCNAME,execresult,errorinfo,createtime,datadate)
    values(''P_BATCH_SEND_REDPAC'',''N'','''||v_errorInfo||''',TO_char(sysdate,''yyyy-mm-dd hh24:mi:ss''),'''||v_today||''')';
    EXECUTE IMMEDIATE v_sql;
    DBMS_OUTPUT.put_line(v_errorInfo);
    COMMIT;
  END;
END P_BATCH_SEND_REDPAC;