--以下存储过程设计表结构
CREATE TABLE "ZHJFUAT"."BZ_DATA_REDPACACT_HIS" (
  "HCNO" VARCHAR2(20) NOT NULL ENABLE,
  "REDID" NUMBER(10) NOT NULL ENABLE,
  "OTHERDESC" VARCHAR2(500),
  "OTHERID" VARCHAR2(50) DEFAULT NULL NOT NULL ENABLE,
  "CHANNELNO" VARCHAR2(8) NOT NULL ENABLE,
  "OTHERACTNO" VARCHAR2(50) DEFAULT NULL NOT NULL ENABLE,
  "SENDSTATUS" VARCHAR2(1) DEFAULT NULL,
  "DATADATE" VARCHAR2(8) DEFAULT NULL NOT NULL ENABLE,
  "CREATEDATE" VARCHAR2(8) DEFAULT NULL NOT NULL ENABLE
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "ZHJFUAT"."BZ_DATA_REDPACACT_HIS" IS '标准数据红包历史表';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."HCNO" IS '核心客户号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."REDID" IS '红包ID';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."OTHERDESC" IS '送券说明';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."OTHERID" IS '三方唯一编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."CHANNELNO" IS '商城提供的渠道编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."OTHERACTNO" IS '三方活动编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."SENDSTATUS" IS '送红包状态：0客户不存在 1已送 2红包数据异常未送 3 超出个人领取上线 4 超出红包领取上线';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."DATADATE" IS '账务日期 YYYYMMDD';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"."CREATEDATE" IS '写入日期 YYYYMMDD';

CREATE TABLE "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING" (
  "HCNO" VARCHAR2(20) NOT NULL ENABLE,
  "REDID" NUMBER(10) NOT NULL ENABLE,
  "OTHERDESC" VARCHAR2(500),
  "OTHERID" VARCHAR2(50) NOT NULL ENABLE,
  "CHANNELNO" VARCHAR2(8) NOT NULL ENABLE,
  "OTHERACTNO" VARCHAR2(50) NOT NULL ENABLE,
  "DATADATE" VARCHAR2(8) NOT NULL ENABLE,
  "CREATEDATE" VARCHAR2(8) NOT NULL ENABLE
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING" IS '标准任务送红包待送表';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."HCNO" IS '核心客户号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."REDID" IS '红包id';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."OTHERDESC" IS '红包描述';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."OTHERID" IS '第三位系统唯一编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."CHANNELNO" IS '商城系统渠道号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."OTHERACTNO" IS '第三方系统活动编号';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."DATADATE" IS '账务日期';
COMMENT ON COLUMN "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"."CREATEDATE" IS '创建日期';

CREATE TABLE "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT" (
  "HCNO" VARCHAR2(20) NOT NULL ENABLE,
  "REDID" NUMBER(10) NOT NULL ENABLE,
  "OTHERDESC" VARCHAR2(500),
  "OTHERID" VARCHAR2(50) NOT NULL ENABLE,
  "CHANNELNO" VARCHAR2(8) NOT NULL ENABLE,
  "OTHERACTNO" VARCHAR2(50) NOT NULL ENABLE
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT" IS '标准任务送红包临时表';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."HCNO" IS '核心客户号';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."REDID" IS '红包id';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."OTHERDESC" IS '红包描述';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."OTHERID" IS '第三位系统唯一编号';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."CHANNELNO" IS '商城系统渠道号';
COMMENT ON COLUMN "ZHJFUAT"."QS_TEMP_BZ_DATA_REDPACACT"."OTHERACTNO" IS '第三方系统活动编号';

CREATE TABLE "EMALLUAT"."MEMBER" (
  "MEMBERNO" NUMBER(31) NOT NULL ENABLE,
  "LOGINNAME" VARCHAR2(60),
  "LOGINPWD" VARCHAR2(255),
  "MEMBERNAME" VARCHAR2(100),
  "IDTYPE" VARCHAR2(10),
  "IDNO" VARCHAR2(25),
  "GENDER" CHAR(1),
  "PHONENO" VARCHAR2(15),
  "EMAIL" VARCHAR2(50),
  "ADDRESS" VARCHAR2(100),
  "MEMBERLEVEL" CHAR(1),
  "MEMBERSTATUS" CHAR(1),
  "CREATETIME" VARCHAR2(20),
  "LASTLOGINTIME" VARCHAR2(20),
  "LOGINTIMES" NUMBER(31),
  "ERRORLOGINTIMES" NUMBER(31),
  "CUSTOMERSID" NUMBER(31),
  "FROMTYPE" VARCHAR2(2),
  "EXSTATE" VARCHAR2(2),
  "ISCOLLECTSINGLE" CHAR(1),
  "CUSTNO" VARCHAR2(18),
  "ISCUSTSERVER" CHAR(1),
  "MEMBERTYPE" CHAR(1),
  "ISSAVEAUTH" CHAR(1),
  "ISMBAUTH" CHAR(1),
  "ROLEID" NUMBER(31),
  "PAYPWD" VARCHAR2(100),
  "SECQUESTION1" VARCHAR2(255),
  "SECANSWER1" VARCHAR2(255),
  "SECQUESTION2" VARCHAR2(255),
  "SECANSWER2" VARCHAR2(255),
  "SECQUESTION3" VARCHAR2(255),
  "SECANSWER3" VARCHAR2(255),
  "LASTLOGINDATE" VARCHAR2(18),
  "ACCOUNTAUTH" CHAR(1),
  "ERRORPAYTIMES" NUMBER(31),
  "SUBTYPE" CHAR(4),
  "IMGURL" VARCHAR2(100),
  "LOCKPAYPASSWORDDATE" VARCHAR2(20),
  "ISLOCKPAYPASSWORD" CHAR(1) DEFAULT '0',
  "LOCKLOGINPASSWORDDATE" VARCHAR2(20),
  "CHANNEL" VARCHAR2(3),
  "ISOPENEMALL" VARCHAR2(1),
  "ISOPENEPAY" VARCHAR2(1),
  "INSTITUTIONID" NUMBER(8),
  "ISBATCH" VARCHAR2(1),
  "NICKNAME" VARCHAR2(100),
  "MEMBERIMAGES" VARCHAR2(500),
  "HOSTCUSTNO" VARCHAR2(32),
  "WECHATPUSH" VARCHAR2(1),
  CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBERNO"),
  CONSTRAINT "MEMBER_IX1" UNIQUE ("LOGINNAME"),
  CONSTRAINT "MEMBER_IX3" UNIQUE ("EMAIL")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."MEMBER" IS '门户会员表';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERNO" IS '会员号<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOGINNAME" IS '会员名<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOGINPWD" IS '登录密码，密文<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERNAME" IS '姓名<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."IDTYPE" IS '证件类型<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."IDNO" IS '证件号码<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."GENDER" IS '性别，1男，2女<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."PHONENO" IS '手机号<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."EMAIL" IS '邮箱<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ADDRESS" IS '地址<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERLEVEL" IS '客户';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERSTATUS" IS '客户状态，1正常，2未激活，3注销，4锁定';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."CREATETIME" IS '创建时间<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LASTLOGINTIME" IS '最近登录时间';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOGINTIMES" IS '累计登录次数<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ERRORLOGINTIMES" IS '累计登录错误次数，每次登录成功后置0，累计5次状态锁定。<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."CUSTOMERSID" IS '客户ID<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."FROMTYPE" IS '会员来源类型 00 自助注册 11 网银自动注册<BR>00 是缺省值<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."EXSTATE" IS '会员扩展状态<BR>00 是缺省值<BR>10 网银自动注册状态<BR>11 已修改设置登录名<BR>12 已修改设置登录密码<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISCOLLECTSINGLE" IS '是否开通商户收单服务 0-开通 1-不开通（默认）<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."CUSTNO" IS '商户号（开通了商户的才会有商户号）<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISCUSTSERVER" IS '是否开通店家服务<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERTYPE" IS '会员类型（个人，企业） 0个人，1企业<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISSAVEAUTH" IS '是否开启安全密码认证 0-开通 1-不开通';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISMBAUTH" IS '<BR>是否开启手机认证 0-开通 1-不开通<BR>';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ROLEID" IS '角色编号';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."PAYPWD" IS '支付密码';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECQUESTION1" IS '安全保护问题1';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECANSWER1" IS '安全保护应答1';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECQUESTION2" IS '安全保护问题2';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECANSWER2" IS '安全保护应答2';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECQUESTION3" IS '安全保护问题3';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SECANSWER3" IS '安全保护应答3';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LASTLOGINDATE" IS '上次登录时间';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ACCOUNTAUTH" IS '账号实名认证标志；0未认证 1已认证；商户审批时必须已认证状态才进入审批状态，未认证提示商户添加银行账号做实名认证；';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ERRORPAYTIMES" IS '错误支付次数';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."SUBTYPE" IS '1001 店铺主账号, 1002 店铺网点子账号, 1003 承运商物流网点子账号,2001 装修公司子账号';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."IMGURL" IS '会员头像';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOCKPAYPASSWORDDATE" IS '支付密码锁定时间';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISLOCKPAYPASSWORD" IS '支付密码是否锁定: 0-不锁定 1-锁定';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."LOCKLOGINPASSWORDDATE" IS '登录密码锁定时间';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."CHANNEL" IS '渠道';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISOPENEMALL" IS '是否开启商城';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISOPENEPAY" IS '是否开启易支付';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."INSTITUTIONID" IS '机构号，批量导入时会数据';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."ISBATCH" IS '是否批量导入，0：是，1：否';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."NICKNAME" IS '昵称';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."MEMBERIMAGES" IS '会员图片';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."HOSTCUSTNO" IS '核心客户号';
COMMENT ON COLUMN "EMALLUAT"."MEMBER"."WECHATPUSH" IS '是否接受微信推送';

CREATE TABLE "EMALLUAT"."REDPACACT" (
  "PACID" NUMBER(31) NOT NULL ENABLE,
  "ACTNAME" VARCHAR2(200) NOT NULL ENABLE,
  "STARTDATE" VARCHAR2(12) DEFAULT NULL NOT NULL ENABLE,
  "ENDDATE" VARCHAR2(12) DEFAULT NULL NOT NULL ENABLE,
  "STARTTIME" VARCHAR2(12) NOT NULL ENABLE,
  "ENDTIME" VARCHAR2(12) NOT NULL ENABLE,
  "AUTHSTATE" VARCHAR2(4) NOT NULL ENABLE,
  "PCINHTMLURL" VARCHAR2(200),
  "PCALERTHEMLURL" VARCHAR2(200),
  "MBINHTMLURL" VARCHAR2(200),
  "MBALERTHEMLURL" VARCHAR2(200),
  "PACTYPE" VARCHAR2(4) NOT NULL ENABLE,
  "FLAG" VARCHAR2(2) NOT NULL ENABLE,
  "BELONGTYPE" VARCHAR2(4) NOT NULL ENABLE,
  "USERULEDESC" VARCHAR2(2000),
  "ORIGINATOR" VARCHAR2(100) NOT NULL ENABLE,
  "SHOPID" NUMBER(31),
  "MAXSEND" NUMBER(31) NOT NULL ENABLE,
  "VALIDAY" NUMBER(8) DEFAULT '0',
  "RPENDTIME" VARCHAR2(30),
  "STATE" VARCHAR2(10),
  "USESTARTTIME" VARCHAR2(30),
  "USEENDTIME" VARCHAR2(30),
  "LIMITCOUNT" NUMBER(8) DEFAULT '1',
  "USEBALANCE" NUMBER(18,2),
  "DAYCNT" NUMBER(8) DEFAULT '1',
  "INSNO" VARCHAR2(8),
  "PACAMTMIN" NUMBER(18,2) NOT NULL ENABLE,
  "PACAMTMAX" NUMBER(18,2),
  "SHOPIDS" VARCHAR2(2000) DEFAULT NULL,
  "REMARK" VARCHAR2(300),
  "ACTTYPE" VARCHAR2(10),
  "CATEGORY2ID" VARCHAR2(2000) DEFAULT NULL,
  "USEDESC" VARCHAR2(200),
  "IMAGEURL" VARCHAR2(200),
  "MATCHTYPE" VARCHAR2(2),
  "GOODSID" VARCHAR2(3000) DEFAULT NULL,
  "LISTATTRIBUTE" VARCHAR2(1),
  "LISTTYPE" VARCHAR2(1),
  "LIMITTYPE" VARCHAR2(1),
  "ISVISIBLE" VARCHAR2(1),
  "ISTRANSFER" VARCHAR2(1),
  "ISBUY" VARCHAR2(3),
  "INSTITUTIONNO" VARCHAR2(10),
  "ISBACK" VARCHAR2(1),
  "BACKINGNUM" NUMBER(8) DEFAULT 1,
  "BZ1" VARCHAR2(20),
  "BZ2" VARCHAR2(20),
  "BZ3" VARCHAR2(20),
  "BZ4" VARCHAR2(20),
  "BZ5" VARCHAR2(20),
  "BZ6" VARCHAR2(20),
  CONSTRAINT "PK_REDPACACT" PRIMARY KEY ("PACID")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."REDPACACT" IS '红包活动表';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PACID" IS '主键，自增长ID';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ACTNAME" IS '红包活动名称';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."STARTDATE" IS '开始日期';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ENDDATE" IS '结束日期';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."STARTTIME" IS '开始时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ENDTIME" IS '结束时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."AUTHSTATE" IS '审核状态: 1001-待审核<BR>1002-审核通过<BR>1003-审核失败<BR>';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PCINHTMLURL" IS 'PC端活动入口页面URL';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PCALERTHEMLURL" IS 'PC端参入活动弹出页面URL';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."MBINHTMLURL" IS '手机端活动入口页面URL';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."MBALERTHEMLURL" IS '手机端参入活动弹出页面URL';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PACTYPE" IS '红包类型 1001-固定,1002-随机固定值,1003-随机区间值';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."FLAG" IS '活动标识 1:注册时领取';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BELONGTYPE" IS '发行方 1001-平台, 1002-店铺';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USERULEDESC" IS '使用规则描述';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ORIGINATOR" IS '发起人';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."SHOPID" IS '店铺ID, 如果BELONGTYPE为2时则必填';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."MAXSEND" IS '最多送出个数';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."VALIDAY" IS '有效期，自活动结束后多少天失效，单位/天';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."RPENDTIME" IS '红包有效日期';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."STATE" IS '00：启用，11：停用';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USESTARTTIME" IS '使用开始时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USEENDTIME" IS '使用结束时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."LIMITCOUNT" IS '活动有效期内可领取数量';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USEBALANCE" IS '使用金额限制';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."DAYCNT" IS '每天可领取数量';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."INSNO" IS '所属机构编号';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PACAMTMIN" IS '红包金额';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."PACAMTMAX" IS '结算金额';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."SHOPIDS" IS '店铺id集合';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."REMARK" IS '审核意见';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ACTTYPE" IS '0：红包 1：优惠券';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."CATEGORY2ID" IS '所属2级类目id';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."USEDESC" IS '图文详情';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."IMAGEURL" IS '代金券图片';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."MATCHTYPE" IS '匹配类型  0-全匹配  1-模糊匹配';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."GOODSID" IS '商品编号';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."LISTATTRIBUTE" IS '名单属性 0-白名单,1-黑名单';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."LISTTYPE" IS '名单类型 0-手机号码,1-客户号';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."LIMITTYPE" IS '允许类型 0-允许店铺,1-允许类目,2-允许商品';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ISVISIBLE" IS '页面是否可见 Y:可见 N:不可见';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ISTRANSFER" IS '是否允许转赠 Y:允许 N:不允许';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ISBUY" IS '是否需要购买 000-不需要购买 001-需要购买';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."INSTITUTIONNO" IS '机构号，关联机构表INSTITUTION';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."ISBACK" IS '可退标志，0-可退，1-不可退';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BACKINGNUM" IS '可退次数，默认1次';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ1" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ2" IS '投放渠道（取自枚举订单渠道）';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ3" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ4" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ5" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."REDPACACT"."BZ6" IS '备用字段';


CREATE TABLE "EMALLUAT"."MYREDPAC" (
  "MYPACID" NUMBER(31) NOT NULL ENABLE,
  "MEMBERNO" NUMBER(31) NOT NULL ENABLE,
  "PACID" NUMBER(31) NOT NULL ENABLE,
  "PACSTATE" VARCHAR2(4) NOT NULL ENABLE,
  "INITAMT" NUMBER(18,2) NOT NULL ENABLE,
  "BELONGTYPE" VARCHAR2(4) NOT NULL ENABLE,
  "CREATETIME" VARCHAR2(30),
  "RECORDID" VARCHAR2(50),
  "REFUNDTIMES" NUMBER(31),
  CONSTRAINT "PK_MYREDPAC" PRIMARY KEY ("MYPACID")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."MYREDPAC" IS '我的红包表';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."MYPACID" IS '主键，自增长ID';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."MEMBERNO" IS '会员号';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."PACID" IS '红包ID';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."PACSTATE" IS '红包状态 <BR>1001-锁定,<BR>1002-正常待使用,<BR>1003-已使用（已下单，未付款）,<BR>1004-退款,1005-过期 <BR>1006-待清算 <BR>1007-已支付（支付成功）<BR>1008-失效状态,1009-已清算';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."INITAMT" IS '原始金额';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."BELONGTYPE" IS '发行方 1001-平台, 1002-店铺';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."RECORDID" IS '手机银行红包记录 32位';
COMMENT ON COLUMN "EMALLUAT"."MYREDPAC"."REFUNDTIMES" IS '商品消费退款后，红包的已退次数';


CREATE TABLE "EMALLUAT"."REDPACAPPLY" (
  "ID" NUMBER(8) NOT NULL ENABLE,
  "BATCHID" VARCHAR2(50),
  "APPLYBY" VARCHAR2(25),
  "APPLYTIME" VARCHAR2(30),
  "SUMCOUNT" NUMBER(8),
  "SUCCCOUNT" NUMBER(8),
  "FAILCOUNT" NUMBER(8),
  "PACID" NUMBER(8),
  "TYPE" VARCHAR2(1),
  "SENDREASON" VARCHAR2(400),
  "SENDACTNO" VARCHAR2(50)
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."REDPACAPPLY" IS '红包清算申请表';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."ID" IS '主键';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."BATCHID" IS '申请批次';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."APPLYBY" IS '申请人';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."APPLYTIME" IS '申请时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."SUMCOUNT" IS '总条数';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."SUCCCOUNT" IS '送红包成功条数';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."FAILCOUNT" IS '送红包失败条数';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."PACID" IS '红包活动Id';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."TYPE" IS '1：手机，2：邮箱，3：会员号';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."SENDREASON" IS '送券说明（esb与优讯渠道送券新增）';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLY"."SENDACTNO" IS '三方活动编号（esb与优讯渠道送券新增）';


CREATE TABLE "EMALLUAT"."REDPACAPPLYDETAIL" (
  "ID" NUMBER(8) NOT NULL ENABLE,
  "PHONENO" VARCHAR2(20),
  "BATCHID" VARCHAR2(50),
  "MEMBERNO" NUMBER(8),
  "EMAIL" VARCHAR2(50),
  "CREATETIME" VARCHAR2(30),
  "STATUS" VARCHAR2(1),
  "CUSTNO" VARCHAR2(30)
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."REDPACAPPLYDETAIL" IS '红包清算申请细节';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."ID" IS '主键';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."PHONENO" IS '手机号';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."BATCHID" IS '批次号';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."MEMBERNO" IS '会员号';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."STATUS" IS '1：待送红包，2：送红包成功，3：送红包失败';
COMMENT ON COLUMN "EMALLUAT"."REDPACAPPLYDETAIL"."CUSTNO" IS '客户号（根据redpacapply表的type字段区分）';


CREATE TABLE "EMALLUAT"."PRIVI_REDPACACT" (
  "ID" NUMBER(31) NOT NULL ENABLE,
  "CUSTTYPE" VARCHAR2(4) NOT NULL ENABLE,
  "CUSTNO" VARCHAR2(20) DEFAULT NULL NOT NULL ENABLE,
  "REDID" NUMBER(31) DEFAULT NULL NOT NULL ENABLE,
  "OTHERDESC" VARCHAR2(500) DEFAULT NULL,
  "OTHERID" VARCHAR2(20) DEFAULT NULL,
  "CHANNELNO" VARCHAR2(8) NOT NULL ENABLE,
  "DATASOURCE" NUMBER(1),
  "OTHERACTNO" VARCHAR2(20),
  "CREATEDATE" VARCHAR2(12) NOT NULL ENABLE,
  "BZ1" VARCHAR2(20) DEFAULT 0,
  "BZ2" VARCHAR2(20),
  "BZ3" VARCHAR2(20),
  "BZ4" VARCHAR2(20),
  "BZ5" VARCHAR2(20),
  "BZ6" VARCHAR2(20),
  "BZ7" VARCHAR2(20),
  "BZ8" VARCHAR2(20),
  "BZ9" VARCHAR2(20),
  "BZ10" VARCHAR2(20),
  "STATUS" NUMBER(1) DEFAULT 0 NOT NULL ENABLE,
  "REDNAME" VARCHAR2(200) DEFAULT NULL,
  "MEMBERNO" NUMBER(31) DEFAULT NULL,
  CONSTRAINT "PK_PRIVI_REDPACACT" PRIMARY KEY ("ID")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 2 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;
COMMENT ON TABLE "EMALLUAT"."PRIVI_REDPACACT" IS '待送红包表';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."ID" IS '主键，自增长ID';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."CUSTTYPE" IS '客户类型：HCNO核心客户号，10 手机号，11 邮箱，12 商城会员号';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."CUSTNO" IS '结合客户类型';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."REDID" IS '红包ID';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."OTHERDESC" IS '送券说明';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."OTHERID" IS '三方唯一编号';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."CHANNELNO" IS '商城提供的渠道编号：商城管理台：000';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."DATASOURCE" IS '数据源：1 积分跑批 2 外放接口 3 商城管理台手工赠送';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."OTHERACTNO" IS '三方活动编号';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."CREATEDATE" IS '日期：YYYYMMDD';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ1" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ2" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ3" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ4" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ5" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ6" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ7" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ8" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ9" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."BZ10" IS '备用字段';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."STATUS" IS '0：启用 1：停用';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."REDNAME" IS '红包名称';
COMMENT ON COLUMN "EMALLUAT"."PRIVI_REDPACACT"."MEMBERNO" IS '商城会员号';





-- ============================================================
-- 生产环境前置要求：以下索引必须在存储过程上线前创建
-- 执行方式：以 DBA 账号在对应 Schema 下执行
-- ============================================================

-- P0 致命级 —— 缺少任何一个，百万级数据无法正常运行
CREATE INDEX "EMALLUAT"."IDX_MEMBER_HOSTCUSTNO"     ON "EMALLUAT"."MEMBER"("HOSTCUSTNO");
CREATE INDEX "EMALLUAT"."IDX_MYREDPAC_MEMBER_PAC"    ON "EMALLUAT"."MYREDPAC"("MEMBERNO", "PACID");
CREATE INDEX "EMALLUAT"."IDX_MYREDPAC_PACID"         ON "EMALLUAT"."MYREDPAC"("PACID");
CREATE INDEX "ZHJFUAT"."IDX_REDPACACT_HIS_DEDUP"     ON "ZHJFUAT"."BZ_DATA_REDPACACT_HIS"("CHANNELNO", "OTHERID", "OTHERACTNO");

-- P1 重要级 —— 大幅提升写入和清理性能
CREATE INDEX "EMALLUAT"."IDX_REDPACAPPLY_BATCHID"    ON "EMALLUAT"."REDPACAPPLY"("BATCHID");
CREATE INDEX "EMALLUAT"."IDX_REDPACAPPLYDETAIL_BID"  ON "EMALLUAT"."REDPACAPPLYDETAIL"("BATCHID");
CREATE INDEX "ZHJFUAT"."IDX_SENDING_CREATEDATE"      ON "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"("CREATEDATE");
CREATE INDEX "ZHJFUAT"."IDX_SENDING_DEL"             ON "ZHJFUAT"."BZ_DATA_REDPACACT_SENDING"("HCNO", "REDID", "OTHERID");

-- P2 建议级
CREATE INDEX "EMALLUAT"."IDX_PRIVI_REDPAC_REDID"     ON "EMALLUAT"."PRIVI_REDPACACT"("REDID");


-- ============================================================
-- 存储过程：P_BATCH_SEND_REDPAC（重构版 v2）
-- 功能：批量送红包
--
-- 【相比 v1 的核心变更】
-- 1. 修复 TO_CHAR 格式掩码 mm→mi（原版将月份写入分钟字段，导致时间比较和记录错误）
-- 2. 预聚合 MYREDPAC 统计替代逐行关联子查询（500万行从 1000万次索引查找 → 2次 GROUP BY）
-- 3. REDPACAPPLY 直接写入正确 SUCCCOUNT/FAILCOUNT，去掉 INSERT-then-UPDATE 反模式
-- 4. REDPACAPPLYDETAIL 直接写入 STATUS='2'，去掉 INSERT('3')-then-UPDATE('2') 反模式
-- 5. 去掉了 temp_final_ok 空表创建再 INSERT 的冗余步骤
-- 6. GTT 清理统一到异常处理块
--
-- 【业务逻辑（与原版一致）】
-- a) 过滤客户不存在的记录 → HIS(0) + PRIVI_REDPACACT
-- b) 过滤无效红包 → HIS(2) + PRIVI_REDPACACT
-- c) 过滤超出个人限制 → HIS(3) + SENDING 重试
-- d) 过滤超出红包总数限制 → HIS(4) + SENDING 重试
-- e) 成功记录 → MYREDPAC + REDPACAPPLY + REDPACAPPLYDETAIL + HIS(1)
-- f) 清理已成功的 SENDING 记录 + 过期数据
--
-- 参数：
--   p_day : 清理超过 p_day 天的待送表历史，0 表示清空整个待送表
-- ============================================================
CREATE OR REPLACE PROCEDURE P_BATCH_SEND_REDPAC(p_day IN NUMBER DEFAULT 30)
IS
    -- 时间变量（FIXED: TO_CHAR 中 mm 改为 mi，mm 在 Oracle 中表示月份而非分钟）
    v_now       VARCHAR2(14);  -- 时间戳
    v_now1      VARCHAR2(19);   -- 送红包明细表时间 YYYY-MM-DD HH24:MI:SS
    v_now2      VARCHAR2(19);   -- 我的红包创建时间 YYYYMMDD HH24:MI:SS
    v_today     VARCHAR2(8);  -- 处理时间经过
    v_batchid   VARCHAR2(20);-- 批次号
    l_accdate   VARCHAR2(8);

    -- 源数据总量
    v_total_source    NUMBER := 0;

    -- 各类处理计数
    v_no_member_cnt   NUMBER := 0;
    v_invalid_pac_cnt NUMBER := 0;
    v_over_limit_cnt  NUMBER := 0;
    v_over_max_cnt    NUMBER := 0;
    v_success_cnt     NUMBER := 0;

    -- 异常处理
    v_error_info      VARCHAR2(4000);

    -- 安全删除临时表
    PROCEDURE safe_drop(p_table IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ' || p_table;
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

BEGIN
    -- =================================================================
    -- 阶段1：初始化
    -- =================================================================
    EXECUTE IMMEDIATE 'SET ob_query_timeout = 86400000000';

    v_now     := TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS');
    v_now1    := TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS');   -- FIXED: mm→mi
    v_now2    := TO_CHAR(SYSDATE, 'YYYYMMDD HH24:MI:SS');     -- FIXED: mm→mi
    v_today   := TO_CHAR(SYSDATE, 'YYYYMMDD');
    v_batchid := 'P' || v_now;

    SELECT sp.sysworkdate INTO l_accdate FROM sysparameter sp;

    DBMS_OUTPUT.PUT_LINE('[P_BATCH_SEND_REDPAC] 开始 | 批次: ' || v_batchid
                      || ' | 时间: ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'));

    -- =================================================================
    -- 阶段2：检查待处理数据
    -- =================================================================
    SELECT COUNT(1) INTO v_total_source
    FROM (
        SELECT 1 FROM ZHJFUAT.QS_TEMP_BZ_DATA_REDPACACT WHERE ROWNUM = 1
        UNION ALL
        SELECT 1 FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING WHERE ROWNUM = 1
    );

    IF v_total_source = 0 THEN
        DBMS_OUTPUT.PUT_LINE('[P_BATCH_SEND_REDPAC] 无待处理数据');
        IF p_day = 0 THEN
            EXECUTE IMMEDIATE 'TRUNCATE TABLE ZHJFUAT.BZ_DATA_REDPACACT_SENDING';
        ELSE
            DELETE FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING
            WHERE CREATEDATE < TO_CHAR(SYSDATE - p_day, 'YYYYMMDD');
        END IF;
        COMMIT;
        RETURN;
    END IF;

    -- =================================================================
    -- 阶段3：预聚合 MYREDPAC 统计数据（替代逐行关联子查询的核心优化）
    -- 一次 GROUP BY 替代 N×2 次关联子查询
    -- =================================================================
    safe_drop('tmp_member_rp_stats');

    EXECUTE IMMEDIATE '
        CREATE GLOBAL TEMPORARY TABLE tmp_member_rp_stats ON COMMIT PRESERVE ROWS AS
        SELECT MEMBERNO, PACID, COUNT(*) AS sent_cnt
        FROM EMALLUAT.MYREDPAC
        GROUP BY MEMBERNO, PACID';

    safe_drop('tmp_pac_total_stats');

    EXECUTE IMMEDIATE '
        CREATE GLOBAL TEMPORARY TABLE tmp_pac_total_stats ON COMMIT PRESERVE ROWS AS
        SELECT PACID, COUNT(*) AS total_sent
        FROM EMALLUAT.MYREDPAC
        GROUP BY PACID';

    -- =================================================================
    -- 阶段4：构建统一源数据 + 客户验证 + 红包验证（一次扫描完成三类判断）
    -- =================================================================
    safe_drop('tmp_source');

    EXECUTE IMMEDIATE '
        CREATE GLOBAL TEMPORARY TABLE tmp_source ON COMMIT PRESERVE ROWS AS
        SELECT
            src.HCNO,
            src.REDID,
            src.OTHERDESC,
            src.OTHERID,
            src.CHANNELNO,
            src.OTHERACTNO,
            src.DATATYPE,
            m.MEMBERNO,
            CASE WHEN m.MEMBERNO IS NULL THEN ''N'' ELSE ''Y'' END AS has_member,
            r.PACID              AS r_pacid,
            NVL(r.PACAMTMIN, 0)  AS pac_amt,
            NVL(r.LIMITCOUNT, 0) AS limit_cnt,
            NVL(r.MAXSEND, 0)    AS max_send,
            CASE
                WHEN r.PACID IS NULL     THEN ''PAC_NOT_EXIST''
                WHEN r.AUTHSTATE != ''1002'' THEN ''AUTH_FAIL''
                WHEN r.STATE != ''00''       THEN ''DISABLED''
                WHEN NVL(r.USEENDTIME, ''9999-12-31 23:59:59'') < ''' || v_now1 || ''' THEN ''EXPIRED''
                ELSE ''VALID''
            END AS pac_status
        FROM (
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, 0 AS DATATYPE
            FROM ZHJFUAT.QS_TEMP_BZ_DATA_REDPACACT
            UNION ALL
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, 1 AS DATATYPE
            FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING
        ) src
        LEFT JOIN EMALLUAT.MEMBER m ON m.HOSTCUSTNO = src.HCNO
        LEFT JOIN EMALLUAT.REDPACACT r ON r.PACID = src.REDID';

    -- 统计源数据总量
    SELECT COUNT(1) INTO v_total_source FROM tmp_source;

    -- =================================================================
    -- 阶段5：处理客户不存在的记录
    -- =================================================================
    SELECT COUNT(1) INTO v_no_member_cnt FROM tmp_source WHERE has_member = 'N';

    IF v_no_member_cnt > 0 THEN
        -- 写入 SENDING（仅 DATATYPE=0，即 QS_TEMP 来源）
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_SENDING
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''' || l_accdate || ''', ''' || v_today || '''
            FROM tmp_source WHERE has_member = ''N'' AND DATATYPE = 0';

        -- 写入 HIS（SENDSTATUS=0，仅 DATATYPE=0）
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
             SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''0'', ''' || l_accdate || ''', ''' || v_today || '''
            FROM tmp_source WHERE has_member = ''N'' AND DATATYPE = 0';

        -- 写入 PRIVI_REDPACACT（仅 DATATYPE=0 且 REDID 在 REDPACACT 中存在）
        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.PRIVI_REDPACACT
            (ID, CUSTTYPE, CUSTNO, REDID, OTHERDESC, OTHERID, CHANNELNO,
             DATASOURCE, OTHERACTNO, CREATEDATE, STATUS)
            SELECT EMALLUAT.S_PRIVI_REDPACACT.NEXTVAL,
                   ''HCNO'', HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO,
                   1, OTHERACTNO, ''' || v_today || ''', 0
            FROM tmp_source
            WHERE has_member = ''N'' AND DATATYPE = 0
              AND r_pacid IS NOT NULL';
    END IF;

    -- =================================================================
    -- 阶段6：对有效红包 + 有效客户的记录，计算个人限制和总量限制
    -- 使用预聚合的 MYREDPAC 统计数据 JOIN，替代逐行关联子查询
    -- =================================================================
    safe_drop('tmp_limit_checked');

    EXECUTE IMMEDIATE '
        CREATE GLOBAL TEMPORARY TABLE tmp_limit_checked ON COMMIT PRESERVE ROWS AS
        WITH personal_check AS (
            SELECT
                t.HCNO, t.REDID, t.OTHERDESC, t.OTHERID, t.CHANNELNO, t.OTHERACTNO,
                t.DATATYPE, t.MEMBERNO, t.pac_amt, t.limit_cnt, t.max_send,
                NVL(s.sent_cnt, 0) AS sent_by_member,
                ROW_NUMBER() OVER(PARTITION BY t.MEMBERNO, t.REDID ORDER BY t.OTHERID) AS rn_member,
                CASE
                    WHEN NVL(s.sent_cnt, 0) + ROW_NUMBER() OVER(PARTITION BY t.MEMBERNO, t.REDID ORDER BY t.OTHERID)
                         <= t.limit_cnt THEN ''Y''
                    ELSE ''N''
                END AS personal_ok
            FROM tmp_source t
            LEFT JOIN tmp_member_rp_stats s ON s.MEMBERNO = t.MEMBERNO AND s.PACID = t.REDID
            WHERE t.has_member = ''Y''
              AND t.pac_status = ''VALID''
        )
        SELECT
            pc.*,
            NVL(pt.total_sent, 0) AS sent_total,
            ROW_NUMBER() OVER(PARTITION BY pc.REDID ORDER BY pc.OTHERID) AS rn_total,
            CASE
                WHEN NVL(pt.total_sent, 0) + ROW_NUMBER() OVER(PARTITION BY pc.REDID ORDER BY pc.OTHERID)
                     <= pc.max_send THEN ''Y''
                ELSE ''N''
            END AS total_ok
        FROM personal_check pc
        LEFT JOIN tmp_pac_total_stats pt ON pt.PACID = pc.REDID';

    -- 统计各类结果
    SELECT COUNT(1) INTO v_success_cnt
    FROM tmp_limit_checked WHERE personal_ok = 'Y' AND total_ok = 'Y';

    SELECT COUNT(1) INTO v_over_limit_cnt
    FROM tmp_limit_checked WHERE personal_ok = 'N';

    SELECT COUNT(1) INTO v_over_max_cnt
    FROM tmp_limit_checked WHERE personal_ok = 'Y' AND total_ok = 'N';

    SELECT COUNT(1) INTO v_invalid_pac_cnt
    FROM tmp_source WHERE has_member = 'Y' AND pac_status != 'VALID';

    -- =================================================================
    -- 阶段7：写入各类失败记录
    -- =================================================================

    -- 7.1 无效红包 → HIS(2) + PRIVI_REDPACACT（仅 DATATYPE=0）
    IF v_invalid_pac_cnt > 0 THEN
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
             SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''2'', ''' || l_accdate || ''', ''' || v_today || '''
            FROM tmp_source
            WHERE has_member = ''Y'' AND pac_status != ''VALID'' AND DATATYPE = 0';

        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.PRIVI_REDPACACT
            (ID, CUSTTYPE, CUSTNO, REDID, OTHERDESC, OTHERID, CHANNELNO,
             DATASOURCE, OTHERACTNO, CREATEDATE, STATUS, MEMBERNO)
            SELECT EMALLUAT.S_PRIVI_REDPACACT.NEXTVAL,
                   ''HCNO'', HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO,
                   1, OTHERACTNO, ''' || v_today || ''', 0, MEMBERNO
            FROM tmp_source
            WHERE has_member = ''Y'' AND pac_status != ''VALID'' AND DATATYPE = 0
              AND r_pacid IS NOT NULL';
    END IF;

    -- 7.2 超出个人限制 → HIS(3) + SENDING 重试（仅 DATATYPE=0）
    IF v_over_limit_cnt > 0 THEN
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_SENDING
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''' || l_accdate || ''', ''' || v_today || '''
            FROM tmp_limit_checked WHERE personal_ok = ''N'' AND DATATYPE = 0';

        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
             SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''3'', ''' || l_accdate || ''', ''' || v_today || '''
            FROM tmp_limit_checked WHERE personal_ok = ''N'' AND DATATYPE = 0';
    END IF;

    -- 7.3 超出红包总量限制 → HIS(4) + SENDING 重试（仅 DATATYPE=0）
    IF v_over_max_cnt > 0 THEN
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_SENDING
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''' || l_accdate || ''', ''' || v_today || '''
            FROM tmp_limit_checked
            WHERE personal_ok = ''Y'' AND total_ok = ''N'' AND DATATYPE = 0';

        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
             SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''4'', ''' || l_accdate || ''', ''' || v_today || '''
            FROM tmp_limit_checked
            WHERE personal_ok = ''Y'' AND total_ok = ''N'' AND DATATYPE = 0';
    END IF;

    -- =================================================================
    -- 阶段8：写入成功记录（单事务，保证原子性）
    -- =================================================================
    IF v_success_cnt > 0 THEN

        -- 8.1 REDPACAPPLY：直接写入正确的 SUCCCOUNT/FAILCOUNT（去掉了 INSERT-then-UPDATE）
        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.REDPACAPPLY
            (ID, BATCHID, APPLYBY, APPLYTIME, SUMCOUNT, SUCCCOUNT, FAILCOUNT, PACID, TYPE, SENDREASON, SENDACTNO)
            SELECT EMALLUAT.S_REDPACAPPLY.NEXTVAL,
                   ''' || v_batchid || ''',
                   CHANNELNO,
                   ''' || v_now1 || ''',
                   cnt, cnt, 0,
                   REDID,
                   ''4'',
                   OTHERDESC,
                   OTHERACTNO
            FROM (
                SELECT REDID, CHANNELNO, OTHERDESC, OTHERACTNO, COUNT(*) AS cnt
                FROM tmp_limit_checked
                WHERE personal_ok = ''Y'' AND total_ok = ''Y''
                GROUP BY REDID, CHANNELNO, OTHERDESC, OTHERACTNO
            )';

        -- 8.2 REDPACAPPLYDETAIL：直接写入 STATUS='2'（去掉了 INSERT('3')-then-UPDATE('2')）
        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.REDPACAPPLYDETAIL
            (ID, PHONENO, BATCHID, MEMBERNO, EMAIL, CREATETIME, STATUS, CUSTNO)
            SELECT EMALLUAT.S_REDPACAPPLYDETAIL.NEXTVAL,
                   NULL,
                   ''' || v_batchid || ''',
                   MEMBERNO,
                   NULL,
                   ''' || v_now1 || ''',
                   ''2'',
                   HCNO
            FROM tmp_limit_checked
            WHERE personal_ok = ''Y'' AND total_ok = ''Y''';

        -- 8.3 MYREDPAC：写入用户红包
        EXECUTE IMMEDIATE '
            INSERT INTO EMALLUAT.MYREDPAC
            (MYPACID, MEMBERNO, PACID, PACSTATE, INITAMT, BELONGTYPE, CREATETIME, RECORDID, REFUNDTIMES)
            SELECT EMALLUAT.S_MYREDPAC.NEXTVAL,
                   MEMBERNO,
                   REDID,
                   ''1002'',
                   pac_amt,
                   ''1001'',
                   ''' || v_now2 || ''',
                   NULL,
                   0
            FROM tmp_limit_checked
            WHERE personal_ok = ''Y'' AND total_ok = ''Y''';

        -- 8.4 HIS：成功记录（NOT EXISTS 去重，按 CHANNELNO+OTHERID+OTHERACTNO）
        EXECUTE IMMEDIATE '
            INSERT INTO ZHJFUAT.BZ_DATA_REDPACACT_HIS
            (HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
             SENDSTATUS, DATADATE, CREATEDATE)
            SELECT HCNO, REDID, OTHERDESC, OTHERID, CHANNELNO, OTHERACTNO,
                   ''1'', ''' || l_accdate || ''', ''' || v_today || '''
            FROM tmp_limit_checked src
            WHERE personal_ok = ''Y'' AND total_ok = ''Y''
              AND NOT EXISTS (
                  SELECT 1 FROM ZHJFUAT.BZ_DATA_REDPACACT_HIS his
                  WHERE his.CHANNELNO  = src.CHANNELNO
                    AND his.OTHERID    = src.OTHERID
                    AND his.OTHERACTNO = src.OTHERACTNO
              )';

        -- 8.5 从 SENDING 中删除已成功处理的 DATATYPE=1 记录
        EXECUTE IMMEDIATE '
            DELETE FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING s
            WHERE EXISTS (
                SELECT 1 FROM tmp_limit_checked t
                WHERE t.personal_ok = ''Y'' AND t.total_ok = ''Y''
                  AND t.DATATYPE = 1
                  AND t.HCNO = s.HCNO
                  AND t.REDID = s.REDID
                  AND t.OTHERID = s.OTHERID
            )';
    END IF;

    -- =================================================================
    -- 阶段9：清理过期待送表数据
    -- =================================================================
    IF p_day = 0 THEN
        EXECUTE IMMEDIATE 'TRUNCATE TABLE ZHJFUAT.BZ_DATA_REDPACACT_SENDING';
    ELSE
        DELETE FROM ZHJFUAT.BZ_DATA_REDPACACT_SENDING
        WHERE CREATEDATE <= TO_CHAR(SYSDATE - p_day, 'YYYYMMDD');
    END IF;

    -- =================================================================
    -- 阶段10：提交事务 + 清理临时表
    -- =================================================================
    COMMIT;

    safe_drop('tmp_member_rp_stats');
    safe_drop('tmp_pac_total_stats');
    safe_drop('tmp_source');
    safe_drop('tmp_limit_checked');

    -- =================================================================
    -- 阶段11：输出处理摘要
    -- =================================================================
    DBMS_OUTPUT.PUT_LINE('==========================================');
    DBMS_OUTPUT.PUT_LINE('[P_BATCH_SEND_REDPAC] 处理完成 | 批次: ' || v_batchid);
    DBMS_OUTPUT.PUT_LINE('  源数据总量:      ' || v_total_source);
    DBMS_OUTPUT.PUT_LINE('  客户不存在:      ' || v_no_member_cnt);
    DBMS_OUTPUT.PUT_LINE('  无效红包:        ' || v_invalid_pac_cnt);
    DBMS_OUTPUT.PUT_LINE('  超出个人限制:    ' || v_over_limit_cnt);
    DBMS_OUTPUT.PUT_LINE('  超出总量限制:    ' || v_over_max_cnt);
    DBMS_OUTPUT.PUT_LINE('  成功发送:        ' || v_success_cnt);
    DBMS_OUTPUT.PUT_LINE('  清理超过 ' || p_day || ' 天的待送表数据');
    DBMS_OUTPUT.PUT_LINE('==========================================');

EXCEPTION
    WHEN OTHERS THEN
        -- 记录错误信息
        v_error_info := 'SQLCODE=' || SQLCODE || ' | SQLERRM=' || SQLERRM || CHR(10)
                     || 'BACKTRACE=' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

        -- 清理所有临时表
        safe_drop('tmp_member_rp_stats');
        safe_drop('tmp_pac_total_stats');
        safe_drop('tmp_source');
        safe_drop('tmp_limit_checked');

        ROLLBACK;

        -- 写入错误日志（对单引号做转义）
        EXECUTE IMMEDIATE '
            INSERT INTO t_proc_oper_log(PROCNAME, execresult, errorinfo, createtime, datadate)
            VALUES(''P_BATCH_SEND_REDPAC'', ''N'', '''
                || REPLACE(v_error_info, '''', '''''') || ''',
                TO_CHAR(SYSDATE, ''YYYY-MM-DD HH24:MI:SS''),
                ''' || v_today || ''')';

        COMMIT;

        DBMS_OUTPUT.PUT_LINE('[P_BATCH_SEND_REDPAC] 异常: ' || v_error_info);
        RAISE;
END P_BATCH_SEND_REDPAC;